name: blood_donor_manger
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  auto_route: ^7.8.0
  url_strategy: ^0.2.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_smart_dialog: ^4.9.8+9
  google_fonts: ^6.3.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  cloud_firestore:  ^6.0.0
  firebase_storage: ^13.0.0
  material_design_icons_flutter: ^7.0.7296
  image_picker: ^1.1.2
  intl: ^0.20.2
  animated_bottom_navigation_bar: ^1.4.0
  badges: ^3.1.2
  url_launcher: ^6.3.2
  place_picker_v2: ^0.0.2
  data_table_2: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6

  auto_route_generator: ^7.3.0

dependency_overrides:
      win32: ^5.14.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logos/

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image_dark: assets/logos/logo_normal.png
  icon_background_color_dark: "#ffffff"
  image: assets/logos/logo_normal.png
  android: true
  ios: true
  fullscreen: true
  android_12:
    image: assets/logos/logo_android_12.png
    icon_background_color: "#ffffff"
    image_dark: assets/logos/logo_android_12.png
    icon_background_color_dark: "#ffffff"

    

    # flutter packages pub run build_runner build --delete-conflicting-outputs